[package]
name = "lab1"
version = "0.1.0"
authors = ["Isaac Sikkema <isikkema@tennessee.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
glam = "0.15"
clap = "2.33"
rangle = {path = "rangle"}