[package]
name = "rangle"
version = "0.1.0"
authors = ["Isaac Sikkema <isaacsikkema@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
rand = "0.8"
thiserror = "1.0"
glam = "0.15"
